script
errorLine5/farmace_server pull request #53
Opened 2024-10-28 13:51 UTC by PietroTiro

script db

2024-11-04 10:45 UTC, Shiberal commented on template_sqlite.sql
@Sbelo2003 , @PietroTiro  ma.. a sto punto ci serve indirizzo?

2024-11-04 10:55 UTC, Sbelo2003 commented on template_sqlite.sql
forse ho capito che intendi, ma mo mi viene un dubbio, tu visto che ti tiri dietro le coordinate l'indirizzo non lo possiamo prendere a partire da esse? nel senso si cerca tramite oordinate poi ci sara un indirizzo associato o sbaglio?

2024-11-05 11:07 UTC, Shiberal requested changes
indirizzo = "cap, comune, provincia, regione, nazione"

2024-11-05 11:07 UTC, Shiberal commented on template_sqlite.sql
>      indirizzo TEXT NOT NULL UNIQUE,
indirizzo = "cap, comune, provincia, regione, nazione" ??

2024-11-12 08:34 UTC, closed without merging

2024-11-12 08:35 UTC, Shiberal commented on template_sqlite.sql
> +    nazione TEXT NOT NULL,
no